
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Fri Feb 22 20:34:43 ART 2019
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "ejemplo", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ejemplo", namespace = "http://ws.das.ubp.edu.ar/")

public class Ejemplo {


}

