
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Sun Feb 18 14:00:32 ART 2018
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "getCuentasClientesResponse", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCuentasClientesResponse", namespace = "http://ws.das.ubp.edu.ar/")

public class GetCuentasClientesResponse {

    @XmlElement(name = "return")
    private java.util.List<ar.edu.ubp.das.src.beans.CuentaBean> _return;

    public java.util.List<ar.edu.ubp.das.src.beans.CuentaBean> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<ar.edu.ubp.das.src.beans.CuentaBean> new_return)  {
        this._return = new_return;
    }

}

