
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Thu Apr 19 21:00:54 ART 2018
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "notificarGanador", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notificarGanador", namespace = "http://ws.das.ubp.edu.ar/", propOrder = {"id_portal","id_concesionaria", "dni_cliente", "id_plan",  "fecha_sorteo"})

public class NotificarGanador {

	@XmlElement(name = "id_portal")
    private java.lang.String id_portal;
  	@XmlElement(name = "id_concesionaria")
    private java.lang.String id_concesionaria;
    @XmlElement(name = "dni_cliente")
    private java.lang.String dni_cliente;
    @XmlElement(name = "id_plan")
    private java.lang.String id_plan;
    @XmlElement(name = "fecha_sorteo")
    private java.lang.String fecha_sorteo;

    public java.lang.String getId_portal() {
		return id_portal;
	}

	public void setId_portal(java.lang.String id_portal) {
		this.id_portal = id_portal;
	}
	
    public java.lang.String getIdConcesionaria() {
        return this.id_concesionaria;
    }

    public void setIdConcesionaria(java.lang.String newArg0)  {
        this.id_concesionaria = newArg0;
    }

    public java.lang.String getDniCliente() {
        return this.dni_cliente;
    }

    public void setDniCliente(java.lang.String newArg1)  {
        this.dni_cliente = newArg1;
    }

	public java.lang.String getId_plan() {
		return id_plan;
	}

	public void setId_plan(java.lang.String id_plan) {
		this.id_plan = id_plan;
	}

    public java.lang.String getFechaSorteo() {
        return this.fecha_sorteo;
    }

    public void setFechaSorteo(java.lang.String newArg4)  {
        this.fecha_sorteo = newArg4;
    }

}

