
package ar.edu.ubp.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Sun Feb 18 14:00:32 ART 2018
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "getCuentasClientes", namespace = "http://ws.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCuentasClientes", namespace = "http://ws.das.ubp.edu.ar/")

public class GetCuentasClientes {


}

