
package ar.edu.ubp.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-04-23T23:20:24.905-03:00
 * Generated source version: 3.1.7
 * 
 */
public final class ClientesWS_ClientesWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.ubp.edu.ar/", "ClientesWSService");

    private ClientesWS_ClientesWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClientesWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClientesWSService ss = new ClientesWSService(wsdlURL, SERVICE_NAME);
        ClientesWS port = ss.getClientesWSPort();  
        
        {
        System.out.println("Invoking getCuentasClientes...");
        try {
            java.lang.String _getCuentasClientes__return = port.getCuentasClientes();
            System.out.println("getCuentasClientes.result=" + _getCuentasClientes__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificarCancelado...");
        java.lang.String _verificarCancelado_arg0 = "_verificarCancelado_arg0-1496344030";
        java.lang.String _verificarCancelado__return = port.verificarCancelado(_verificarCancelado_arg0);
        System.out.println("verificarCancelado.result=" + _verificarCancelado__return);


        }
        {
        System.out.println("Invoking notificarGanador...");
        java.lang.String _notificarGanador_arg0 = "_notificarGanador_arg0762390291";
        java.lang.String _notificarGanador_arg1 = "_notificarGanador_arg11679380768";
        java.lang.String _notificarGanador_arg2 = "_notificarGanador_arg2-651432234";
        java.lang.String _notificarGanador_arg3 = "_notificarGanador_arg3190776562";
        java.lang.String _notificarGanador_arg4 = "_notificarGanador_arg41260458771";
        java.lang.String _notificarGanador__return = port.notificarGanador(_notificarGanador_arg0, _notificarGanador_arg1, _notificarGanador_arg2, _notificarGanador_arg3, _notificarGanador_arg4);
        System.out.println("notificarGanador.result=" + _notificarGanador__return);


        }

        System.exit(0);
    }

}
