package ar.edu.ubp.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-04-23T23:20:24.999-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "ClientesWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ClientesWS {

    @WebMethod(action = "urn:GetCuentasClientes")
    @RequestWrapper(localName = "getCuentasClientes", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetCuentasClientes")
    @ResponseWrapper(localName = "getCuentasClientesResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetCuentasClientesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCuentasClientes() throws Exception_Exception;

    @WebMethod(action = "urn:VerificarCancelado")
    @RequestWrapper(localName = "verificarCancelado", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.VerificarCancelado")
    @ResponseWrapper(localName = "verificarCanceladoResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.VerificarCanceladoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verificarCancelado(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(action = "urn:NotificarGanador")
    @RequestWrapper(localName = "notificarGanador", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.NotificarGanador")
    @ResponseWrapper(localName = "notificarGanadorResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.NotificarGanadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String notificarGanador(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );
}
