package ar.edu.ubp.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-05-08T20:43:40.378-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "ConcesionariaRossoWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ConcesionariaRossoWS {

    @WebMethod(action = "urn:GetClientes")
    @RequestWrapper(localName = "getClientes", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetClientes")
    @ResponseWrapper(localName = "getClientesResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetClientesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getClientes() throws Exception_Exception;

    @WebMethod(action = "urn:VerificarCancelado")
    @RequestWrapper(localName = "verificarCancelado", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.VerificarCancelado")
    @ResponseWrapper(localName = "verificarCanceladoResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.VerificarCanceladoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String verificarCancelado(
        @WebParam(name = "dni_cliente", targetNamespace = "")
        java.lang.String dniCliente,
        @WebParam(name = "id_plan", targetNamespace = "")
        java.lang.String idPlan
    ) throws Exception_Exception;

    @WebMethod(action = "urn:NotificarGanador")
    @RequestWrapper(localName = "notificarGanador", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.NotificarGanador")
    @ResponseWrapper(localName = "notificarGanadorResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.NotificarGanadorResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String notificarGanador(
        @WebParam(name = "id_portal", targetNamespace = "")
        java.lang.String idPortal,
        @WebParam(name = "id_concesionaria", targetNamespace = "")
        java.lang.String idConcesionaria,
        @WebParam(name = "dni_cliente", targetNamespace = "")
        java.lang.String dniCliente,
        @WebParam(name = "nombre_apellido", targetNamespace = "")
        java.lang.String nombreApellido,
        @WebParam(name = "id_plan", targetNamespace = "")
        java.lang.String idPlan,
        @WebParam(name = "fecha_sorteo", targetNamespace = "")
        java.lang.String fechaSorteo
    ) throws Exception_Exception;
}
