
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-04-30T09:17:24.257-03:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "ConcesionariaRossoWSService",
                      portName = "ConcesionariaRossoWSPort",
                      targetNamespace = "http://ws.das.ubp.edu.ar/",
                      wsdlLocation = "http://localhost:9090/ConcesionariaRossoWSPort?wsdl",
                      endpointInterface = "ar.edu.ubp.das.ws.ConcesionariaRossoWS")
                      
public class ConcesionariaRossoWSPortImpl implements ConcesionariaRossoWS {

    private static final Logger LOG = Logger.getLogger(ConcesionariaRossoWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.ConcesionariaRossoWS#getClientes()*
     */
    public java.lang.String getClientes() throws Exception_Exception   { 
        LOG.info("Executing operation getClientes");
        try {
            java.lang.String _return = "_return1117164511";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.ConcesionariaRossoWS#verificarCancelado(java.lang.String dniCliente, java.lang.String idPlan)*
     */
    public java.lang.String verificarCancelado(java.lang.String dniCliente, java.lang.String idPlan) throws Exception_Exception   { 
        LOG.info("Executing operation verificarCancelado");
        System.out.println(dniCliente);
        System.out.println(idPlan);
        try {
            java.lang.String _return = "_return971773271";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see ar.edu.ubp.das.ws.ConcesionariaRossoWS#notificarGanador(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4)*
     */
    public java.lang.String notificarGanador(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4) throws Exception_Exception   { 
        LOG.info("Executing operation notificarGanador");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.lang.String _return = "_return-936555458";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
