
package ar.edu.ubp.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-05-08T20:43:40.253-03:00
 * Generated source version: 3.1.7
 * 
 */
public final class ConcesionariaRossoWS_ConcesionariaRossoWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.ubp.edu.ar/", "ConcesionariaRossoWSService");

    private ConcesionariaRossoWS_ConcesionariaRossoWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConcesionariaRossoWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConcesionariaRossoWSService ss = new ConcesionariaRossoWSService(wsdlURL, SERVICE_NAME);
        ConcesionariaRossoWS port = ss.getConcesionariaRossoWSPort();  
        
        {
        System.out.println("Invoking getClientes...");
        try {
            java.lang.String _getClientes__return = port.getClientes();
            System.out.println("getClientes.result=" + _getClientes__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificarCancelado...");
        java.lang.String _verificarCancelado_dniCliente = "_verificarCancelado_dniCliente405866632";
        java.lang.String _verificarCancelado_idPlan = "_verificarCancelado_idPlan-1303337749";
        try {
            java.lang.String _verificarCancelado__return = port.verificarCancelado(_verificarCancelado_dniCliente, _verificarCancelado_idPlan);
            System.out.println("verificarCancelado.result=" + _verificarCancelado__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notificarGanador...");
        java.lang.String _notificarGanador_idPortal = "_notificarGanador_idPortal-1545517097";
        java.lang.String _notificarGanador_idConcesionaria = "_notificarGanador_idConcesionaria-95253904";
        java.lang.String _notificarGanador_dniCliente = "_notificarGanador_dniCliente-770039940";
        java.lang.String _notificarGanador_nombreApellido = "_notificarGanador_nombreApellido-550663225";
        java.lang.String _notificarGanador_idPlan = "_notificarGanador_idPlan-1842903886";
        java.lang.String _notificarGanador_fechaSorteo = "_notificarGanador_fechaSorteo-1902429018";
        try {
            java.lang.String _notificarGanador__return = port.notificarGanador(_notificarGanador_idPortal, _notificarGanador_idConcesionaria, _notificarGanador_dniCliente, _notificarGanador_nombreApellido, _notificarGanador_idPlan, _notificarGanador_fechaSorteo);
            System.out.println("notificarGanador.result=" + _notificarGanador__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
