
package ar.edu.ubp.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-02-12T14:00:26.484-03:00
 * Generated source version: 3.1.7
 * 
 */
public final class EstadosClientes_EstadosClientesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.ubp.edu.ar/", "EstadosClientesService");

    private EstadosClientes_EstadosClientesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EstadosClientesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EstadosClientesService ss = new EstadosClientesService(wsdlURL, SERVICE_NAME);
        EstadosClientes port = ss.getEstadosClientesPort();  
        
        {
        System.out.println("Invoking getEstados...");
        java.lang.String _getEstados__return = port.getEstados();
        System.out.println("getEstados.result=" + _getEstados__return);


        }

        System.exit(0);
    }

}
