package ar.edu.ubp.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-02-12T14:00:26.561-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ws.das.ubp.edu.ar/", name = "EstadosClientes")
@XmlSeeAlso({ObjectFactory.class})
public interface EstadosClientes {

    @WebMethod(action = "urn:GetEstados")
    @RequestWrapper(localName = "getEstados", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetEstados")
    @ResponseWrapper(localName = "getEstadosResponse", targetNamespace = "http://ws.das.ubp.edu.ar/", className = "ar.edu.ubp.das.ws.GetEstadosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getEstados();
}
