package ar.edu.ubp.das.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-02-12T14:00:26.568-03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "EstadosClientesService", 
                  wsdlLocation = "http://localhost:9090/EstadosClientesPort?wsdl",
                  targetNamespace = "http://ws.das.ubp.edu.ar/") 
public class EstadosClientesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.das.ubp.edu.ar/", "EstadosClientesService");
    public final static QName EstadosClientesPort = new QName("http://ws.das.ubp.edu.ar/", "EstadosClientesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/EstadosClientesPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EstadosClientesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/EstadosClientesPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EstadosClientesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EstadosClientesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstadosClientesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EstadosClientesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EstadosClientesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EstadosClientesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EstadosClientes
     */
    @WebEndpoint(name = "EstadosClientesPort")
    public EstadosClientes getEstadosClientesPort() {
        return super.getPort(EstadosClientesPort, EstadosClientes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstadosClientes
     */
    @WebEndpoint(name = "EstadosClientesPort")
    public EstadosClientes getEstadosClientesPort(WebServiceFeature... features) {
        return super.getPort(EstadosClientesPort, EstadosClientes.class, features);
    }

}
