
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-02-22T20:44:21.505-03:00
 * Generated source version: 3.1.6
 * 
 */
 
public class ConcesionariaRossoWS_PortTypeServer{

    protected ConcesionariaRossoWS_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.ConcesionariaRossoWS();
        String address = "http://localhost:9191/ConcesionariaRossoWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ConcesionariaRossoWS_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 