
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-02-14T21:20:27.038-03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class EstadosClientesWS_PortTypeServer{

    protected EstadosClientesWS_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.EstadosClientesWS();
        String address = "http://localhost:9090/EstadosClientesWSPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new EstadosClientesWS_PortTypeServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 