<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="EstadosClientesWSService" targetNamespace="http://ws.das.ubp.edu.ar/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.das.ubp.edu.ar/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://ws.das.ubp.edu.ar/" schemaLocation="estadosclientesws_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getEstadosResponse">
    <wsdl:part name="parameters" element="tns:getEstadosResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getEstados">
    <wsdl:part name="parameters" element="tns:getEstados">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="EstadosClientesWS">
    <wsdl:operation name="getEstados">
      <wsdl:input name="getEstados" message="tns:getEstados">
    </wsdl:input>
      <wsdl:output name="getEstadosResponse" message="tns:getEstadosResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EstadosClientesWSServiceSoapBinding" type="tns:EstadosClientesWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getEstados">
      <soap:operation soapAction="urn:GetEstados" style="document"/>
      <wsdl:input name="getEstados">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getEstadosResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EstadosClientesWSService">
    <wsdl:port name="EstadosClientesWSPort" binding="tns:EstadosClientesWSServiceSoapBinding">
      <soap:address location="http://localhost:8080/Concesionaria-Rosso-CXF/services/EstadosClientesWSPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
